eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/students/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**

