server:
  port: 9090

spring:
  application:
    name: microservice-course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  instance:
    hostname: microservice-eureka
  client:
    service-url:
      defaultZone: http://microservice-eureka:8761/eureka/
